### ISSUE TITLE
File number and line no. issue

### ISSUE THREAD

**Issue by 121arunkumar** [mwellner/angular-logging#3]
previously  i was getting file name as "main.js"  after every run,then i enable source map after this i m getting app.component.ts in file name . and also  line no is same.please help me on this.

{
"message": "Error message",
      "additional": [],
      "level": 5,
      "timestamp": "2020-01-29T07:11:27.380Z",
      "fileName": "./src/app/app.component.ts",
      "lineNumber": "12",
      "id": 74
    },
    {
      "message": "Error message",
      "additional": [],
      "level": 5,
      "timestamp": "2020-01-29T07:17:13.073Z",
      "fileName": "./src/app/app.component.ts",
      "lineNumber": "12",
      "id": 75
    }

**Comment by ArpithaGMGowda** [comment]
Yes even i am facing the same problem 

kindly help on this :)

**Comment by mwellner** [comment]
I tried to reproduce the issue. On Firefox, the line number did not work, but on Chrome, it showed the correct line numbers. I have updated the repository, please give it another try.
